# Development override for docker-compose
version: '3.8'

services:
  backend:
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DEBUG=epa:*
    command: npm run dev:watch
    
  admin-portal:
    volumes:
      - ./admin-portal:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    command: npm run dev
    
  mobile:
    volumes:
      - ./mobile:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    command: npx expo start --dev-client --clear