version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: epa_ethics_db
    environment:
      POSTGRES_DB: epa_ethics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend API Server
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: epa_ethics_backend
    environment:
      NODE_ENV: development
      PORT: 3001
      DATABASE_URL: postgresql://postgres:password123@postgres:5432/epa_ethics
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      CORS_ORIGIN: http://localhost:3000,http://localhost:19006
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    command: npm run dev
    restart: unless-stopped

  # Admin Portal (Next.js)
  admin-portal:
    build:
      context: ./admin-portal
      dockerfile: Dockerfile
    container_name: epa_ethics_admin
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:3001
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: your-super-secret-nextauth-key-change-in-production
    ports:
      - "3000:3000"
    volumes:
      - ./admin-portal:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    command: npm run dev
    restart: unless-stopped

  # Mobile App Development Server
  mobile:
    build:
      context: ./mobile
      dockerfile: Dockerfile
    container_name: epa_ethics_mobile
    environment:
      NODE_ENV: development
      EXPO_DEVTOOLS_LISTEN_ADDRESS: 0.0.0.0
      REACT_NATIVE_PACKAGER_HOSTNAME: localhost
    ports:
      - "19000:19000"  # Expo DevTools
      - "19001:19001"  # Expo DevTools
      - "19002:19002"  # Expo DevTools
      - "19006:19006"  # Web version
    volumes:
      - ./mobile:/app
      - /app/node_modules
    depends_on:
      - backend
    command: npm start
    restart: unless-stopped
    stdin_open: true
    tty: true

  # Redis for session storage and caching
  redis:
    image: redis:7-alpine
    container_name: epa_ethics_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  default:
    name: epa_ethics_network